version: '3.5'

services:
    parser:
        container_name: parser_bases
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=root
        image: postgres:14.5-alpine3.16